export const MESSAGE_CONSTANT = {
  // EMPTY_PASSWORD: 'Mật khẩu không được để trống',
  // CREATE_NEW_UNIT_SUCCESS: 'Tạo đơn vị thành công',
  // CREATE_NEW_UNIT_FAIL: 'Tạo đơn vị thất bại',
  // UPDATE_UNIT_SUCCESS: 'Cập nhật đơn vị thành công',
  // UPDATE_UNIT_FAIL: 'Cập nhật đơn vị thất bại',
  // REMOVE_UNIT_SUCCESS: 'Xóa đơn vị thành công',
  // REMOVE_UNIT_FAIL: 'Xóa đơn vị thất bại',
  // LIST_EMPLOYEE_ONL_SUCCESS: 'Tải danh sách hồ sơ điện tử thành công',
  // CREATE_ACCOUNT_SUCCESS: 'Tạo tài khoản thành công',
  // LIST_ROLE_ONL_SUCCESS: 'Tải danh sách nhóm quyền thành công',
  // DELETE_ROLE_ONL_SUCCESS: 'Xóa nhóm quyền thành công',
  // DELETE_ROLE_ONL_FAILED: 'Xóa nhóm quyền thất bại',
  // UPLOAD_FILES_SUCCESS: 'Tải hình ảnh thành công',
  // UPLOAD_FILES_FAIL: 'Tải hình ảnh thất bại',
  // OLD_PASSWORD_INCORRECT: 'Mật khẩu cũ không đúng',
  // LIST_APPOINTMENT_SUCCESS: 'Tải danh sách lịch hẹn thành công',
  // UPDATE_STATUS_APPOINTMENT_SUCCESS: 'Cập nhật trạng thái lịch hẹn thành công',
  // USER_PROFILE_SUCCESS: 'Tải hồ sơ cá nhân thành công',
  // CHANGE_PASSWORD_SUCCESS: 'Thay đổi mật khẩu thành công',
  // SEND_EMAIL_SUCCESS: 'Gửi Email thành công',
  // LIST_ASSET_SUCCESS: 'Tải danh sách thiết bị thành công',
  // CREATE_ASSET_MAINTENANCE_SUCCESS: 'Tạo phiếu bảo trì thành công',
  // CREATE_ASSET_DELIVERY_SUCCESS: 'Tạo phiếu bàn giao thành công',
  // CREATE_ASSET_SUCCESS: 'Tạo thiết bị thành công',
  // UPDATE_STATUS_ASSET_SUCCESS: 'Cập nhật trạng thái thiết bị thành công',
  // UPDATE_ASSET_SUCCESS: 'Sửa thiết bị thành công',
};
